apiVersion: v1
data:
  cluster.name: example-eks-name
  http.port: "2020"
  http.server: "On"
  logs.region: sa-east-1
  read.head: "Off"
  read.tail: "On"
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch